//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinepolilla.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int No_Peli { get; set; }
        public string Nombre { get; set; }
        public string Sipnosis { get; set; }
        public System.DateTime Fecha_estreno { get; set; }
        public System.DateTime Fecha_limite { get; set; }
        public int Restriccion_edad { get; set; }
        public decimal Precio { get; set; }
    }
}
